// ============================================================
// ゲーム定数 — 時間倍率、世界サイズ、バランスパラメータ
// ============================================================

export const WORLD_WIDTH = 1600
export const WORLD_HEIGHT = 800
export const GRID_SIZE = 5

export const TIME_CONFIG = {
  REAL_SECONDS_PER_GAME_DAY: 120,
  START_YEAR: 1522,
  START_MONTH: 1,
  START_DAY: 1,
  DAYS_PER_YEAR: 365,
  DAYS_PER_MONTH: [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31] as readonly number[],
} as const

export const NAVIGATION_CONFIG = {
  BASE_SPEED_FACTOR: 1.0,
  WIND_EFFECT_FACTOR: 0.8,
  CURRENT_EFFECT_FACTOR: 0.3,
  MAX_SPEED: 25,
  BASE_TURN_RATE: 45,
  LOW_CREW_SPEED_FACTOR: 0.62,
  LOW_CREW_TURN_FACTOR: 0.7,
  MINIMUM_MOVABLE_CREW_FACTOR: 0.35,
  LOW_MORALE_SPEED_FACTOR: 0.84,
  LOW_MORALE_TURN_FACTOR: 0.88,
  HIGH_MORALE_SPEED_BONUS: 1.04,
  HIGH_MORALE_TURN_BONUS: 1.05,
} as const

export const ECONOMY_CONFIG = {
  PRICE_VOLATILITY: 0.15,
  RESTOCK_RATE: 5,
  MAX_PRICE_MULTIPLIER: 3.0,
  MIN_PRICE_MULTIPLIER: 0.3,
  TRADE_IMPACT_FACTOR: 0.02,
} as const

export const COMBAT_CONFIG = {
  BASE_CANNON_DAMAGE: 10,
  BASE_MELEE_DAMAGE: 5,
  CRITICAL_RATE: 0.1,
} as const

export const EXP_CONFIG = {
  LEVEL_UP_FACTOR: 100,
  MAX_LEVEL: 75,
} as const

export const VOYAGE_CONFIG = {
  FOOD_CONSUMPTION_PER_CREW_PER_DAY: 0.32,
  WATER_CONSUMPTION_PER_CREW_PER_DAY: 0.38,
  PASSIVE_MORALE_LOSS_PER_DAY: 0.9,
  STARVATION_ATTRITION_FACTOR: 1.2,
  DEHYDRATION_ATTRITION_FACTOR: 1.8,
  SHORTAGE_MORALE_DAMAGE_FACTOR: 6,
  SHORTAGE_DURABILITY_DAMAGE_FACTOR: 0.9,
  TAVERN_MEAL_COST_PER_CREW: 5,
  TAVERN_ROUND_BASE_COST: 90,
  TAVERN_MEAL_MORALE_RECOVERY: 10,
  TAVERN_ROUND_MORALE_RECOVERY: 20,
  TAVERN_RECRUIT_DISCOUNT_PER_LEVEL: 1,
  EMERGENCY_REPAIR_COST_PER_POINT: 4,
  EMERGENCY_REPAIR_EFFICIENCY: 0.72,
  STANDARD_REPAIR_COST_PER_POINT: 5,
  OVERHAUL_COST_PER_POINT: 7,
  VOYAGE_EVENT_CHANCE_PER_DAY: 0.38,
} as const

export const INITIAL_PLAYER = {
  MONEY: 10000,
  HP: 100,
  ADVENTURE_LEVEL: 1,
  TRADE_LEVEL: 1,
  COMBAT_LEVEL: 1,
  START_PORT: 'lisbon',
  START_NATIONALITY: 'portugal' as const,
} as const

export const LOOP_CONFIG = {
  FIXED_TIMESTEP: 1000 / 60,
  MAX_FRAME_SKIP: 5,
  SLOW_FRAME_THRESHOLD: 50,
} as const
